language: node_js

node_js:
  - "10"

cache:
  yarn: true
  directories:
    - "node_modules"
    
env:
  -|
    test="
    aaa
    bbb
    ccc
    "

script:
  - env
  - yarn run lint
  - yarn run test
