language: node_js

node_js:
  - "10"

cache:
  yarn: true
  directories:
    - "node_modules"
    
matrix:
  include:
  # First test cross-OS packaging using most-significant examples:
  - os: linux
    node_js: v10.0.0
    env:
    - test="
      aaa
      bbb
      ccc
      "

script:
  - env
  - echo "${test}"
  - echo "$test"
  - echo $test
  - yarn run lint
  - yarn run test
